---
- include: variable-check.yml
  vars:
    playbook: deploy.yml

- name: Deploy Craft site
  hosts: web:&{{ env }}
  remote_user: "{{ web_user }}"

  vars:
    deploy_build_before: "{{ playbook_dir }}/deploy-hooks/build-before.yml"
    deploy_build_after: "{{ playbook_dir }}/roles/deploy/hooks/build-after.yml"
    deploy_finalize_after: "{{ playbook_dir }}/roles/deploy/hooks/finalize-after.yml"
    project: "{{ craft_sites[site] }}"
    project_root: "{{ www_root }}/{{ site }}"
    craft_env_defaults:
      db_host: localhost
      db_name: "{{ site | underscore }}_{{ env }}"
      db_user: "{{ site | underscore }}"
      craft_env: "{{ env }}"
      craft_home: "{{ project.ssl.enabled | default(false) | ternary('https', 'http') }}://${HTTP_HOST}"
    site_env: "{{ craft_env_defaults | combine(project.env | default({}), vault_craft_sites[site].env) }}"

  pre_tasks:
    - name: Ensure site is valid
      connection: local
      fail:
        msg: "Site `{{ site | default('') }}` is not valid. Available sites to deploy: {{ craft_sites.keys() | join(', ') }}"
      when: craft_sites[site | default('')] is not defined

    - name: Ensure repo is valid
      connection: local
      fail:
        msg: |
          Invalid Git repository.
          Ensure that your site's `repo` variable is defined in `group_vars/{{ env }}/craft_sites.yml` and uses the SSH format (example: git@github.com:roots/bedrock.git)
          More info:
          > https://roots.io/trellis/docs/deploys/
      when: project.repo is not defined or not project.repo | match(".*@.*:.*\.git")

  roles:
    - deploy
