---
- name: Craft Installed?
  stat: path={{ project_current_path }}/app
  register: craft_installed
  changed_when: false
  failed_when: craft_installed.stat.isdir is not defined

- name: Reload php-fpm
  shell: sudo service php7.0-fpm reload
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
    warn: false
